name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/werify-frontend/web"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "${{ secrets.GITLAB_USERNAME }}"
        GITLAB_PASSWORD: "${{ secrets.GITLAB_PASSWORD }}"
        GITLAB_PROJECT_ID: "${{ secrets.GITLAB_PROJECT_ID }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
